feat: migrate to [lms-image-builder](https://github.com/LMSCloudPaulD/lms-image-builder)
- Remove arm dependencies now avaiable at community repositories.
- Remove Dockerfile backup.
- Remove old build scripts.
- Remove deb package as it is no longer static.
- Add .gitignore.

diff --git a/dists/lmscloud/Dockerfile b/dists/lmscloud/Dockerfile
--- a/dists/lmscloud/Dockerfile
+++ b/dists/lmscloud/Dockerfile
@@ -1,26 +1,38 @@
-ARG arch
-
 # Base it on Debian 11
 FROM debian:bullseye AS base
 
+# Define build argument for the .deb package
+ARG KOHA_PACKAGE
+
+# Check if KOHA_PACKAGE is set and fail the build if it is not
+RUN if [ -z "$KOHA_PACKAGE" ]; then echo "KOHA_PACKAGE argument not provided" && exit 1; fi
+
 # File Author / Maintainer
-# Author if this file is Tomás Cohen Arazi, modified by Paul Derscheid
 LABEL maintainer="paul.derscheid@lmscloud.de"
 
-ENV PATH /usr/bin:/bin:/usr/sbin:/sbin
-ENV DEBIAN_FRONTEND noninteractive
+# Set environment variables
+ENV PATH="/usr/bin:/bin:/usr/sbin:/sbin" \
+    DEBIAN_FRONTEND="noninteractive" \
+    LANGUAGE="en_US.UTF-8" \
+    LANG="en_US.UTF-8" \
+    LC_ALL="en_US.UTF-8" \
+    LC_CTYPE="en_US.UTF-8" \
+    REFRESHED_AT="2023-03-20"
 
-# Set suitable debian sources
-# RUN echo "deb http://httpredir.debian.org/debian bullseye main" > /etc/apt/sources.list
+# Update and install necessary packages first
+RUN apt-get update && apt-get install -y --no-install-recommends \
+    locales \
+    && rm -rf /var/lib/apt/lists/*
 
-ENV REFRESHED_AT 2023-03-20
+# Now configure locales
+RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
+    && echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen \
+    && locale-gen \
+    && dpkg-reconfigure locales \
+    && /usr/sbin/update-locale LANG=en_US.UTF-8
 
-#RUN apt-get -y update
-
-# Install apache2 and testting deps
-# netcat: used for checking the DB is up
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends \
+# Continue with other installations
+RUN apt-get update && apt-get install -y --no-install-recommends \
       apache2 \
       build-essential \
       codespell \
@@ -48,67 +60,41 @@ RUN apt-get update && \
       curl \
       apt-transport-https \
       mlocate \
-      iproute2 && \
-      rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
-
-# Set locales
-RUN    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
-    && echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen \
-    && locale-gen \
-    && dpkg-reconfigure locales \
-    && /usr/sbin/update-locale LANG=en_US.UTF-8
-
-ENV LANGUAGE en_US.UTF-8
-ENV LANG en_US.UTF-8
-ENV LC_ALL en_US.UTF-8
-ENV LC_CTYPE en_US.UTF-8
+      iproute2 \
+    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
 
 # Prepare apache configuration
 RUN a2dismod mpm_event && \
     a2dissite 000-default && \
-    a2enmod rewrite \
-            headers \
-            proxy_http \
-            cgi
+    a2enmod rewrite headers proxy_http cgi
 
 # Add Koha development repositories
-RUN echo "deb [signed-by=/usr/share/keyrings/koha-keyring.gpg] http://debian.koha-community.org/koha-staging dev main" >> /etc/apt/sources.list.d/koha.list && \
-    echo "deb [signed-by=/usr/share/keyrings/koha-deps-keyring.gpg] http://deb3.kohaaloha.com/ka/koha-deps stable main bullseye" >> /etc/apt/sources.list.d/koha.list && \
-    wget -qO - http://debian.koha-community.org/koha/gpg.asc | gpg --dearmor -o /usr/share/keyrings/koha-keyring.gpg && \
-    wget -qO - http://deb3.kohaaloha.com/ka/koha-deps/gpg.asc | gpg --dearmor -o /usr/share/keyrings/koha-deps-keyring.gpg && \
-    apt-get update && \
-    apt-cache policy koha-common && \
-    apt-cache policy libmojolicious-perl && \
-    apt-cache policy libjson-validator-perl && \
-    apt-cache policy libmojolicious-plugin-openapi-perl && \
-    apt-cache policy libyaml-libyaml-perl && \
-    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
+RUN echo "deb [signed-by=/usr/share/keyrings/koha-keyring.gpg] http://debian.koha-community.org/koha-staging dev main" >> /etc/apt/sources.list.d/koha.list \
+    && echo "deb [signed-by=/usr/share/keyrings/koha-deps-keyring.gpg] http://deb3.kohaaloha.com/ka/koha-deps stable main bullseye" >> /etc/apt/sources.list.d/koha.list \
+    && wget -qO - http://debian.koha-community.org/koha/gpg.asc | gpg --dearmor -o /usr/share/keyrings/koha-keyring.gpg \
+    && wget -qO - http://deb3.kohaaloha.com/ka/koha-deps/gpg.asc | gpg --dearmor -o /usr/share/keyrings/koha-deps-keyring.gpg \
+    && apt-get update \
+    && apt-cache policy koha-common \
+    && apt-cache policy libmojolicious-perl \
+    && apt-cache policy libjson-validator-perl \
+    && apt-cache policy libmojolicious-plugin-openapi-perl \
+    && apt-cache policy libyaml-libyaml-perl \
+    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
 
-FROM base AS branch-aarch64
-# COPY arm_dependencies /kohadevbox/arm_dependencies
+# Conditional build for different architectures
+# ARG arch
+# FROM base AS branch-aarch64
+# # ARM-specific setup here
 
-# RUN for f in /kohadevbox/arm_dependencies/*.deb; do gdebi -n "$f"; done && \
-#     rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
+# FROM base AS branch-x86_64
+# # x86_64-specific setup here
 
-# WORKDIR /kohadevbox/arm_dependencies/libhttpd-bench-apachebench-perl
-# RUN tar xf libhttpd-bench-apachebench-perl_0.73.orig.tar.gz
+# FROM branch-${arch} AS final
 
-# WORKDIR /kohadevbox/arm_dependencies/libhttpd-bench-apachebench-perl/ApacheBench-0.73
-# RUN perl Makefile.PL \
-#     && make \
-#     && make install
-
-WORKDIR /kohadevbox
-
-FROM base AS branch-x86_64
-FROM branch-${arch} AS final
-
-# We need to add our lmscloud package instead of fetching from the community repo
-COPY koha-common_21.05.14lmscloud-1_all.deb /kohadevbox/
-
-# Install koha-common
+# Copy and install Koha package
+COPY ${KOHA_PACKAGE} /kohadevbox/
 RUN apt-get update && apt-get install -y --no-install-recommends dpkg \
-    && apt install -y ./koha-common_21.05.14lmscloud-1_all.deb \
+    && apt-get install -y ./kohadevbox/${KOHA_PACKAGE} \
     && apt-get -f install -y --fix-missing \
     && /etc/init.d/koha-common stop \
     && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
@@ -126,18 +112,17 @@ RUN apt-get update && \
     libwebservice-ils-perl \
     libselenium-remote-driver-perl \
     libauth-googleauth-perl \
-    libemail-address-perl && \
-    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
+    libemail-address-perl \
+    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
 
-## Add Yarn
-# Add node repo
-RUN wget -q -O- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
-    echo "deb http://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/node.list && \
-    wget -q -O- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
-    echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
-    apt-get update && \
-    apt-get install -y --no-install-recommends nodejs yarn && \
-    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
+# Add Yarn and Node.js
+RUN wget -q -O- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
+    && echo "deb http://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/node.list \
+    && wget -q -O- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
+    && echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends nodejs yarn \
+    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
 
 # Install gulp
 RUN npm install gulp-cli -g
@@ -153,7 +138,7 @@ RUN cd /kohadevbox \
     && git clone https://gitlab.com/koha-community/koha-gitify.git gitify \
     && git clone https://gitlab.com/koha-community/qa-test-tools.git
 
-# release-tools and koha-howto
+# Release-tools and koha-howto
 RUN cd /kohadevbox && \
     git clone https://gitlab.com/koha-community/release-tools.git && \
     apt-get update && \
@@ -161,8 +146,8 @@ RUN cd /kohadevbox && \
         libhtml-tableextract-perl \
         libtext-multimarkdown-perl \
         bugz \
-        librest-client-perl && \
-    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
+        librest-client-perl \
+    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
 
 # Remote debugger
 RUN cd /kohadevbox \
@@ -176,6 +161,5 @@ COPY files/run.sh /kohadevbox
 COPY files/templates /kohadevbox/templates
 COPY env/defaults.env /kohadevbox/templates/defaults.env
 
-CMD ["/bin/bash", "/kohadevbox/run.sh"]
-
 EXPOSE 8080 8081
+CMD ["/bin/bash", "/kohadevbox/run.sh"]
